[[plugins]]
repo = 'Shougo/dpp.vim'
hook_add = '''
command! DppRemakeState if denops#server#status() == 'running' | call dpp#make_state() | endif
'''

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
hook_add = '''
command! DppInstall call dpp#async_ext_action('installer', 'install')
command! DppUpdate call dpp#async_ext_action('installer', 'update')
'''

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

