
import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_latte.toml"]

[font]
size = 9.0

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[window]
startup_mode = "Maximized"
