[[plugins]]
repo = 'Shougo/dpp.vim'
on_cmd = ['DppInstall', 'DppUpdate']
rtp = ''
hook_source = '''
function! DppRemakeState() abort
  if denops#server#status() != 'running'
    return
  endif
  call dpp#make_state(g:dpp_base, '$BASE_DIR/dpp.ts'->expand())
endfunction
command! DppRemakeState call DppRemakeState()
command! DppInstall call dpp#async_ext_action('installer', 'install')
command! DppUpdate call dpp#async_ext_action('installer', 'update')
'''

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp.vim'
