" vimrc
" 参考
" https://github.com/Shougo/shougo-s-github

" options --------------------
if &compatible
  set nocompatible
endif
set mouse=
set number relativenumber
set shortmess=aTIcFoOsSW showtabline=0 laststatus=0
set noruler noshowcmd noshowmode
set shiftwidth=2 tabstop=2 expandtab
set splitright
set helplang=ja,en
if '+termguicolors'->exists() && !has('gui_running')
  set termguicolors
endif

try
  set cmdheight=0
  augroup ZeroHeightCmdline
    autocmd!
    autocmd CmdlineEnter,RecordingEnter * set cmdheight=1
    autocmd CmdlineLeave,RecordingLeave * set cmdheight=0
  augroup END
catch
  set cmdheight=1
endtry

" autocmd --------------------
augroup ToggleRelativeNumber
  autocmd!
  autocmd CmdlineEnter * if &number |
        \   set norelativenumber | redraw |
        \ endif
  autocmd CmdlineLeave * if &number |
        \   set relativenumber |
        \ endif
augroup END

"--------------------
colorscheme industry
source ~/.config/nvim/rc/keymap.vim
execute 'source' '<sfile>'->expand()->fnamemodify(':h') .. '/dpp.vim'
