" vimrc
" 参考
" https://github.com/Shougo/shougo-s-github

" options --------------------
if &compatible
  set nocompatible
endif
set mouse=
set number relativenumber
set shortmess=aTIcFoOsSW showtabline=0 laststatus=0
set noruler noshowcmd noshowmode
set shiftwidth=2 tabstop=2 expandtab
set splitright
set helplang=ja,en
set cmdheight=1
if '+termguicolors'->exists() && !has('gui_running')
  set termguicolors
endif

"try
"  set cmdheight=0
"  augroup ZeroHeightCmdline
"    autocmd!
"    autocmd CmdlineEnter,RecordingEnter * set cmdheight=1
"    autocmd CmdlineLeave,RecordingLeave * set cmdheight=0
"  augroup END
"catch
"  set cmdheight=1
"endtry

" autocmd --------------------
augroup ToggleRelativeNumber
  autocmd!
  autocmd CmdlineEnter * if &number |
        \   set norelativenumber | redraw |
        \ endif
  autocmd CmdlineLeave * if &number |
        \   set relativenumber |
        \ endif
augroup END

"--------------------
let rc_path = '<sfile>'->expand()->fnamemodify(':h')
execute 'source' rc_path .. '/keymap.vim'
execute 'source' rc_path .. '/dpp.vim'

colorscheme industry
