# Distro env
source /etc/os-release

source $HOME/zsh/p10k.sh
source $HOME/zsh/path.sh
source $HOME/zsh/source.sh
source $HOME/zsh/bind.sh
source $HOME/zsh/complete.sh
source $HOME/zsh/alias.sh
source $HOME/zsh/function.sh
source $HOME/zsh/zeno/zeno.zsh

# XWindowの起動
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  echo -n "Start XWindow? [Y/n] (default: Yes): "
  read ans
  case "$ans" in
    [Nn]* )
      ;;
    * )
      exec startx
      ;;
  esac
fi

if [[ -d "$HOME/miniforge3" ]]; then
  __conda_setup="$($HOME/miniforge3/bin/conda 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
      eval "$__conda_setup"
  else
      if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
          . "$HOME/miniforge3/etc/profile.d/conda.sh"
      else
          export PATH="$HOME/miniforge3/bin:$PATH"
      fi
  fi
  unset __conda_setup
fi

if [ -f "$HOME/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "$HOME/miniforge3/etc/profile.d/mamba.sh"
fi

neofetch
